#!/bin/bash
# Looks through the staging directory to try finding any files older than a minute that the watcher didn't find.
find /cis/www-etc/lib/Gustavus/Resources/jsStaging/ -type f -mmin +1 -exec /cis/lib/Gustavus/Resources/Scripts/manageNewFile {} 'Old file' \;