#!/bin/bash

# Watch for new files and run manageNewFile on any new one we see.
/usr/bin/inotifywait -m -e create --format %f /cis/www-etc/lib/Gustavus/Resources/jsStaging 2>&- |
  while read file
    do
      /cis/lib/Gustavus/Resources/Scripts/manageNewFile $file &
    done